/* sitemap.xml and robots.txt. Every public page except 404.html, with lastmod taken from the content's own
   verification date where it has one (never the build date, so builds stay reproducible). */
'use strict';
const fs = require('fs'), path = require('path');
const P = require('./partials');

module.exports = (all, ctx, outSoFar) => {
  const root = all.siteDir;
  const pages = new Set();
  for (const f of fs.readdirSync(root)) if (f.endsWith('.html') && f !== '404.html') pages.add(f);
  for (const k of Object.keys(outSoFar)) if (k.endsWith('.html') && k !== '404.html') pages.add(k);
  for (const s of all.scenarios || []) pages.add(`experience/${s.slug}.html`);

  const lastmod = {};
  const latest = ds => ds.filter(Boolean).sort().pop();
  for (const m of all.modules) lastmod[m.id + '.html'] = latest(m.topicsData.map(T => T.verified && T.verified.date));
  for (const s of all.scenarios || []) lastmod[`experience/${s.slug}.html`] = s.verified && (s.verified.date || s.verified);
  if (all.toolkit) {
    for (const g of all.toolkit.guides) lastmod[`toolkit/${g.id}.html`] = g.verified && g.verified.date;
    lastmod['toolkit.html'] = latest(all.toolkit.guides.map(g => g.verified && g.verified.date));
  }
  if (all.external) lastmod['resources.html'] = all.external.verified;

  const order = p => p === 'index.html' ? 0 : p.includes('/') ? 2 : 1;
  const list = [...pages].sort((a, b) => order(a) - order(b) || a.localeCompare(b));
  const loc = p => P.site.url + (p === 'index.html' ? '' : p);
  const day = d => typeof d === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(d) ? d : null;
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by tools/build.js (tools/lib/build-seo.js). Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${list.map(p => `  <url><loc>${loc(p)}</loc>${day(lastmod[p]) ? `<lastmod>${lastmod[p]}</lastmod>` : ''}</url>`).join('\n')}
</urlset>
`;
  /* GitHub Pages serves this project under /power-bi/, and crawlers read robots.txt only at the host root, so this file
     documents intent rather than controlling anything. Submit the sitemap in Google Search Console / Bing Webmaster Tools. */
  const robots = `# GENERATED by tools/build.js (tools/lib/build-seo.js).
# Crawlers read robots.txt only at the root of a host. This site is served under /power-bi/, so this copy is
# informational; submit ${P.site.url}sitemap.xml to search consoles directly.
User-agent: *
Allow: /

Sitemap: ${P.site.url}sitemap.xml
`;
  return { 'sitemap.xml': xml, 'robots.txt': robots };
};
