/* sw.js: the offline cache. The precache list is every page, script, style sheet and icon the site needs
   (data files and lazily loaded answers are cached the first time they're used), and the version is a hash
   of their contents, so every deploy that changes a file refreshes visitors' caches automatically. */
'use strict';
const fs = require('fs'), path = require('path'), crypto = require('crypto');
module.exports = (all, ctx, outSoFar) => {
  const root = all.root;
  const list = new Set(['./', '404.html', 'manifest.webmanifest']);
  const add = rel => list.add(rel.split(path.sep).join('/'));
  for (const f of fs.readdirSync(root)) if (f.endsWith('.html')) add(f);
  for (const s of all.scenarios || []) add(`experience/${s.slug}.html`);
  for (const d of ['assets/css', 'assets/js', 'assets/icons']) {
    const dir = path.join(root, d);
    for (const f of fs.readdirSync(dir)) if (/\.(css|js|svg|png)$/.test(f)) add(`${d}/${f}`);
  }
  for (const m of all.modules) add(`${m.id}.html`);
  if (all.toolkit) {
    add('toolkit.html'); add('assets/js/toolkit.js');
    for (const d of all.toolkit.doors) add(`toolkit/${d.id}.html`);
    for (const g of all.toolkit.guides) add(`toolkit/${g.id}.html`);
  }
  add('assets/js/meta.js'); add('assets/js/experience.js'); add('assets/js/templates.js'); add('assets/js/search-index.js');
  for (const d of all.datasets) add(`data/${d.key}.csv`);
  const files = [...list].sort((a, b) => a === './' ? -1 : b === './' ? 1 : a < b ? -1 : 1);
  /* version: hash of the precached files as they will be after this build */
  const h = crypto.createHash('sha256');
  for (const f of files) {
    if (f === './') continue;
    const generated = outSoFar && outSoFar[f];
    const p = path.join(root, f);
    h.update(f + '\0' + (generated !== undefined ? generated : fs.existsSync(p) ? fs.readFileSync(p) : ''));
  }
  const version = 'pbi-holy-grail-' + h.digest('hex').slice(0, 12);
  const src = `/* GENERATED by tools/build.js (tools/lib/build-sw.js). Offline support.
   Pages and data: network first (so updates show up), cache as fallback. Google Fonts: cache first.
   VERSION is a hash of the precached files, so any change refreshes every visitor's cache. */
const VERSION = '${version}';
const CORE = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(CORE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  if (FONT_HOSTS.includes(url.hostname)) {
    e.respondWith(caches.open(VERSION).then(async c => {
      const hit = await c.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok || res.type === 'opaque') c.put(req, res.clone());
      return res;
    }));
    return;
  }
  if (url.origin !== self.location.origin) return;

  e.respondWith((async () => {
    const cache = await caches.open(VERSION);
    const network = fetch(req).then(res => {
      if (res.ok && !url.pathname.endsWith('.zip')) cache.put(req, res.clone());
      return res;
    });
    // wait up to 4 s for the network, then fall back to the cache
    const first = await Promise.race([network.catch(() => null), new Promise(r => setTimeout(r, 4000, null))]);
    if (first) return first;
    const hit = (await cache.match(req, { ignoreSearch: true })) ||
      (req.mode === 'navigate' ? await cache.match('index.html') : undefined);
    if (hit) return hit;
    try { return await network; } catch (err) { return Response.error(); }
  })());
});
`;
  return { 'sw.js': src };
};
