/* GENERATED by tools/build.js (tools/lib/build-sw.js). Offline support.
   Pages and data: network first (so updates show up), cache as fallback. Google Fonts: cache first.
   VERSION is a hash of the precached files, so any change refreshes every visitor's cache. */
const VERSION = 'pbi-holy-grail-1a342e90eaa7';
const CORE = [
  "./",
  "404.html",
  "advanced.html",
  "assets/css/app.css",
  "assets/css/pages.css",
  "assets/css/site.css",
  "assets/icons/apple-touch-icon.png",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/icons/icon-maskable-512.png",
  "assets/icons/icon.svg",
  "assets/js/cards.js",
  "assets/js/content.js",
  "assets/js/course.js",
  "assets/js/diagnostic.js",
  "assets/js/experience.js",
  "assets/js/external.js",
  "assets/js/glossary.js",
  "assets/js/home.js",
  "assets/js/learn.js",
  "assets/js/levelpage.js",
  "assets/js/meta.js",
  "assets/js/paths.js",
  "assets/js/progress.js",
  "assets/js/progresspage.js",
  "assets/js/search-index.js",
  "assets/js/site.js",
  "assets/js/solutions-tracks.js",
  "assets/js/solutions.js",
  "assets/js/templates.js",
  "assets/js/tkguide.js",
  "assets/js/tkhub.js",
  "assets/js/toolkit.js",
  "assets/js/tplpage.js",
  "assets/js/tracks.js",
  "assets/js/xp.js",
  "assets/js/xphub.js",
  "automation.html",
  "beginner.html",
  "cheatsheet.html",
  "data/CustomerTargets.csv",
  "data/DimCustomer.csv",
  "data/DimDate.csv",
  "data/DimEmployee.csv",
  "data/DimProduct.csv",
  "data/DimRegion.csv",
  "data/ExchangeRates.csv",
  "data/FactBudget.csv",
  "data/FactInventory.csv",
  "data/FactSales.csv",
  "data/RawOrdersExport.csv",
  "data/SurveyWide.csv",
  "data/UserRegionMapping.csv",
  "data/WebEvents.csv",
  "diagnostic.html",
  "experience.html",
  "experience/d01-requirements-interview.html",
  "experience/d02-uat-region-total.html",
  "experience/d03-pull-request-review.html",
  "experience/d04-hotfix-or-rollback.html",
  "experience/d05-report-retirement.html",
  "experience/d06-change-requests.html",
  "experience/d07-governance-maturity.html",
  "experience/d08-explain-it-twice.html",
  "experience/s01-executive-sales-dashboard.html",
  "experience/s02-finance-disputes-revenue.html",
  "experience/s03-payroll-security-incident.html",
  "experience/s04-monday-performance-incident.html",
  "experience/s05-one-revenue-semantic-model.html",
  "experience/s06-pbip-merge-conflict.html",
  "experience/s07-test-prod-deployment-failure.html",
  "experience/s08-cfo-refresh-outage.html",
  "experience/s09-fabric-migration-decision.html",
  "experience/s10-bi-architecture-review.html",
  "fabric.html",
  "flashcards.html",
  "glossary.html",
  "governance.html",
  "index.html",
  "intermediate.html",
  "learn.html",
  "manifest.webmanifest",
  "modern.html",
  "progress.html",
  "resources.html",
  "sql.html",
  "templates.html",
  "testing.html",
  "toolkit.html",
  "toolkit/automate-power-bi.html",
  "toolkit/best-practices.html",
  "toolkit/bookshelf.html",
  "toolkit/career-toolkit.html",
  "toolkit/career.html",
  "toolkit/certification-center.html",
  "toolkit/change-radar.html",
  "toolkit/checklists.html",
  "toolkit/dax-debugging.html",
  "toolkit/dax-field-manual.html",
  "toolkit/decision-library.html",
  "toolkit/error-decoder.html",
  "toolkit/fabric-architecture.html",
  "toolkit/first-30-days.html",
  "toolkit/governance-lead.html",
  "toolkit/interview-center.html",
  "toolkit/modeling-patterns.html",
  "toolkit/patterns.html",
  "toolkit/performance-clinic.html",
  "toolkit/power-bi-reference.html",
  "toolkit/power-query-field-guide.html",
  "toolkit/practice-lab.html",
  "toolkit/practice.html",
  "toolkit/production-runbook.html",
  "toolkit/reference.html",
  "toolkit/report-design.html",
  "toolkit/security-field-guide.html",
  "toolkit/senior-handbook.html",
  "toolkit/ship-like-software.html",
  "toolkit/sql-for-bi.html",
  "toolkit/templates-library.html",
  "toolkit/templates.html",
  "toolkit/toolbelt.html",
  "toolkit/tools.html",
  "toolkit/trusted-sources.html",
  "toolkit/whats-broken.html",
  "warehousing.html"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(CORE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  if (FONT_HOSTS.includes(url.hostname)) {
    e.respondWith(caches.open(VERSION).then(async c => {
      const hit = await c.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok || res.type === 'opaque') c.put(req, res.clone());
      return res;
    }));
    return;
  }
  if (url.origin !== self.location.origin) return;

  e.respondWith((async () => {
    const cache = await caches.open(VERSION);
    const network = fetch(req).then(res => {
      if (res.ok && !url.pathname.endsWith('.zip')) cache.put(req, res.clone());
      return res;
    });
    // wait up to 4 s for the network, then fall back to the cache
    const first = await Promise.race([network.catch(() => null), new Promise(r => setTimeout(r, 4000, null))]);
    if (first) return first;
    const hit = (await cache.match(req, { ignoreSearch: true })) ||
      (req.mode === 'navigate' ? await cache.match('index.html') : undefined);
    if (hit) return hit;
    try { return await network; } catch (err) { return Response.error(); }
  })());
});
