/* Builds the site's generated files from content/ and data/.
   Usage (from the project root):
     node tools/build.js           write every generated file
     node tools/build.js --check   write nothing; exit 1 if a generated file is missing or out of date (CI)
   Output goes to site/ (the published website). Generated files start with a "GENERATED" banner.
   Edit content/ instead, then run the build. */
'use strict';
const fs = require('fs'), path = require('path');
const load = require('./lib/load');
const siteDir = load.siteDir;

const BANNER = src => `/* GENERATED by tools/build.js from ${src}. Do not edit by hand: change the source and run "node tools/build.js". */\n`;
const J = v => JSON.stringify(v);
const list = (name, arr) => `const ${name}=[\n${arr.map(J).join(',\n')}\n];\n`;
const map = (name, obj) => `const ${name}={\n${Object.entries(obj).map(([k, v]) => J(k) + ':' + J(v)).join(',\n')}\n};\n`;
const clean = o => JSON.parse(JSON.stringify(o, (k, v) => (k.startsWith('_') || k === 'topicsData') ? undefined : v));

/* topic as the browser sees it */
const topicOut = (T, M) => clean(Object.assign({}, T, { module: M.id }));
const moduleOut = M => clean(Object.assign({}, M, { topics: M.topicsData.map(T => topicOut(T, M)) }));
const solOut = s => { const o = clean(s); if (o.code) o.code = o.code.map(c => c.expect ? [c.lang, c.title, c.src.join('\n'), c.expect] : [c.lang, c.title, c.src.join('\n')]); return o; };

function outputs() {
  const all = load.all();
  const out = {};
  const levels = all.modules.filter(m => m.kind === 'level');

  /* course content: the original globals, same names and shapes */
  const csvText = require('./lib/csv').stringify;
  const DS = {};
  all.datasets.forEach(d => DS[d.key] = { name: d.name, desc: d.desc, cols: d.cols, csv: csvText(d.cols, d.rows).split('\n').slice(1).join('\n').replace(/\n$/, '') });
  out['assets/js/content.js'] = BANNER('content/skills/{beginner,intermediate,advanced}, content/datasets and data/*.csv') +
    `/* DS = practice datasets (rows parsed from compact CSV on first use), LEVELS = Skill Mode levels with their topics. */\n` +
    `const DS=(function(){\nconst P=t=>{const R=[];let r=[],c='',q=false;for(let i=0;i<t.length;i++){const h=t[i];if(q){if(h==='"'){if(t[i+1]==='"'){c+='"';i++}else q=false}else c+=h}else if(h==='"')q=true;else if(h===','){r.push(c);c=''}else if(h==='\\n'){r.push(c);R.push(r);r=[];c=''}else c+=h}r.push(c);R.push(r);return R};\n` +
    map('D', DS) +
    `for(const k in D){const d=D[k];let rows=null;Object.defineProperty(d,'rows',{enumerable:true,get(){return rows||(rows=P(d.csv))}})}\nreturn D})();\n` +
    `const toCSV=ds=>[ds.cols.join(','),...ds.rows.map(r=>r.map(v=>{const s=String(v);return /[",\\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}).join(','))].join('\\n');\n` +
    list('LEVELS', levels.map(moduleOut));

  const levelTopicIds = new Set(levels.flatMap(m => m.topics));
  const sol = {}, tsol = {};
  for (const [id, s] of Object.entries(all.solutions)) (levelTopicIds.has(id.replace(/-\d+$/, '')) ? sol : tsol)[id] = solOut(s);
  out['assets/js/solutions.js'] = BANNER('content/solutions') +
    `/* Worked solutions keyed by assignment id (topicId-index). s = approach, code = [language, title, source],\n   tbl = [header, ...rows], check = values computed from the datasets, note = common mistake. */\n` +
    map('SOLUTIONS', sol) + 'if(typeof TRACK_SOLUTIONS!=="undefined")Object.assign(SOLUTIONS,TRACK_SOLUTIONS);\n';

  out['assets/js/cards.js'] = BANNER('content/flashcards/concepts.json') +
    `/* Concept flashcards. c = category, l = level, q = question, a = answer, x = example, t = what the interviewer checks */\n` +
    list('CONCEPTS', all.concepts);
  out['assets/js/glossary.js'] = BANNER('content/glossary/glossary.json') +
    `/* t = term, k = other spellings, c = category, d = definition, s = related terms */\n` +
    list('GLOSSARY', all.glossary);
  out['assets/js/paths.js'] = BANNER('content/career-paths and content/certifications') +
    list('ROLES', all.roles) + list('CERTS', all.certs.map(c => clean(require('./lib/cert-weights').weigh(c)))) +
    `/* the outline in force today (Microsoft revises exams; versions carry their effective date) */
CERTS.forEach(c=>{const d=new Date(),t=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');const v=c.versions.filter(x=>x.effective<=t).pop()||c.versions[0];c.current=v;c.areas=v.areas;c.next=c.versions.find(x=>x.effective>t)||null});
`;

  for (const ext of extensions) Object.assign(out, ext(all, { BANNER, J, list, map, clean, moduleOut, solOut, tsol }, out));
  return out;
}

/* later build steps (tracks, experience, pages, service worker) register here */
const extensions = [];
for (const f of ['build-tracks', 'build-meta', 'build-experience', 'build-templates', 'build-external', 'build-toolkit', 'build-pages', 'build-search', 'build-sw']) {
  const p = path.join(__dirname, 'lib', f + '.js');
  if (fs.existsSync(p)) extensions.push(require(p));
}

if (require.main === module) {
  const check = process.argv.includes('--check');
  let out;
  try { out = outputs(); } catch (e) { console.error('build failed: ' + e.message); process.exit(1); }
  let changed = 0;
  for (const [rel, text] of Object.entries(out)) {
    const file = path.join(siteDir, rel);
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (cur === text) continue;
    changed++;
    if (check) { console.error('out of date: ' + rel); continue; }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, text);
    console.log('wrote ' + rel);
  }
  if (check && changed) { console.error(`${changed} generated file(s) are out of date. Run: node tools/build.js`); process.exit(1); }
  console.log(`${Object.keys(out).length} generated files ${check ? 'checked' : 'built'}${changed && !check ? `, ${changed} changed` : ', all current'}`);
}
module.exports = { outputs };
